services:
    airflow-init:
      image: apache/airflow:2.9.0-python3.9
      environment:
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        AIRFLOW__CORE__EXECUTOR: LocalExecutor
      depends_on:
        - postgres
      command: >
        bash -c "airflow db migrate &&
        airflow users create --username airflow --firstname Admin --lastname Admin --role Admin --email admin@example.com --password airflow"
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password

    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  airflow-web:
    image: apache/airflow:2.9.0-python3.9
    volumes:
      - ./dags:/opt/airflow/dags
      - ~/airflow_logs:/opt/airflow/logs

    depends_on:
      - postgres
      - minio
    environment:
      _PIP_ADDITIONAL_REQUIREMENTS: "boto3 pandas sqlalchemy psycopg2-binary"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: "RR2OYJg66JvDqfZsHuHhO7cOexmz7Ukd7zSOI0z6VvM="
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_USER: admin
      MINIO_PASSWORD: password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "8081:8080"
    command: webserver
  airflow-scheduler:
    image: apache/airflow:2.9.0-python3.9
    depends_on:
      - postgres
      - minio
    environment:
      _PIP_ADDITIONAL_REQUIREMENTS: "boto3 pandas sqlalchemy psycopg2-binary"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: "RR2OYJg66JvDqfZsHuHhO7cOexmz7Ukd7zSOI0z6VvM="
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_USER: admin
      MINIO_PASSWORD: password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ~/airflow_logs:/opt/airflow/logs
    command: scheduler


volumes:
  postgres_data:
  minio_data:
